### ISSUE TITLE
Document differences to Mammut in README

### ISSUE THREAD

**Issue by klausi** [pwoolcoc/elefren#104]
What are the differences to Mammut? https://github.com/Aaronepower/Mammut
Can you document that in the README so that users can make an educated choice what library they want to use for connecting to Mastodon?
Would it make sense to contribute to Mammut directly to prevent Rust ecosystem fragmentation?

Thanks!

**Comment by pwoolcoc** [comment]
I've added a section to the bottom of the README with the big differences between this and mammut.

I have contributed a few commits to mammut, but have no plans to do so going forward
