### ISSUE TITLE
Remove mention of fork.

### ISSUE THREAD

**Issue by XAMPPRocky** [pwoolcoc/elefren#133]
I have archived mammut redirecting people to elefren. I would prefer you could remove the mention of the fork in the top level description in GitHub, and update other mentions to use the correct link https://github.com/XAMPPRocky/mammut

**Comment by pwoolcoc** [comment]
Thanks, this has been done

**Comment by XAMPPRocky** [comment]
@pwoolcoc The top level GitHub description still uses the wrong link.

**Comment by pwoolcoc** [comment]
yep, sorry, corrected
