### ISSUE TITLE
Support exclude_reblogs option when fetching statuses

### ISSUE THREAD

**Issue by bajtos** [pwoolcoc/elefren#134]
At the moment, elefren's API allows the user to exclude replies when fetching statuses, see 

https://github.com/pwoolcoc/elefren/blob/7786a83a14e4c93098c3ddec7fc03b07807d325c/src/requests/statuses.rs#L39

In Dec 2018, Mastodon has introduced a new parameter `exclude_reblogs` that allows clients to request own statuses only, excluding boosts/reblogs - see https://github.com/tootsuite/mastodon/pull/9640

Can we surface the new option `exclude_reblogs` in elefren's API?

**Comment by pwoolcoc** [comment]
only took me 6 months, sorry for the wait!

**Comment by bajtos** [comment]
> only took me 6 months, sorry for the wait!

Thank you for adding this feature, I appreciate the effort you made to make it happen ❤️ 

There is nothing to apologize for, this is an open source project and you have no obligation to add features requested by strangers like me 😄
